name: CI

# Контролирует, когда запускать workflow
on:
  # Запускается при push или pull request в ветку master
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Позволяет запускать workflow вручную
  workflow_dispatch:

# Описание jobs (заданий), которые выполняются последовательно или параллельно
jobs:
  # Задание для сборки проекта
  build:
    runs-on: ubuntu-latest

    steps:
      # Шаг: Клонирование репозитория
      - uses: actions/checkout@v4

      # Установка JDK
      - name: Set up JDK ${{ matrix.kotlin-version }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Версия JDK от AdoptOpenJDK
          java-version: 17

      # Добавляем шаг для предоставления прав на выполнение файла gradlew
      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      # Установка Gradle для сборки проекта
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      # Запуск сборки проекта
      - name: Build with Gradle
        run: ./gradlew build

      # Запуск тестов
      - name: Run tests
        run: ./gradlew test

      # Настройка кэша Gradle
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle
